spring.application.name=quanlysinhvien
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLySinhVien;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2;sslProtocol=TLS
spring.datasource.username=sa
spring.datasource.password=123123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate Dialect rõ ràng để tránh lỗi "Unable to determine Dialect" nếu mất kết nối tạm thời
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080